### ISSUE TITLE
Add Cryptocurrency Support

### ISSUE THREAD

**Issue by raziel8** [WarenGonzaga/buymeacoffee.js#1]
Add support for bitcoin (and eventually other cryptos), maybe integrating it with BTCPayServer

**Comment by WarenGonzaga** [comment]
Hi @raziel8 thank you for your suggestion however cryptocurrency is not yet supported by the platform.
https://building.buymeacoffee.com/feature-requests/p/cryptocurrency-payment-method

To retrieve data such as currency... please use this identifier.

```text
subscription_currency // for subscriptions
support_currency // for supporters
purchase_currency // for extras
```

Here's the [official documentation](https://developers.buymeacoffee.com/).

**Comment by WarenGonzaga** [comment]
Just heads up... this issue can't make it to the v2 since the API has its own limitation. I will close this one for now and will consider adding this to future if there is an development with the official API. Thank you for reporting!
