### ISSUE TITLE
Transition to Got

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/buymeacoffee.js#10]
This is better than axios and closing #2

**Comment by JohnDoePBabu** [comment]
Noticed that with this change the library will not work for NodeJS versions older than 10.

**Comment by WarenGonzaga** [comment]
I will close this since we transitioned to Got.

**Comment by WarenGonzaga** [comment]
> Noticed that with this change the library will not work for NodeJS versions older than 10.

Let's add this notice... is there any project still uses NodeJS 10 below? this could be an issue as we move forward?

**Comment by JohnDoePBabu** [comment]
The current LTS is 10 and above, the previous one (version 8) went past "end of life" in January 2020. So it is relatively safe for us to stick with v10 or greater as a requirement.
![image](https://user-images.githubusercontent.com/20773727/97669952-438d5e00-1aab-11eb-967f-e90f5a2837c1.png)
But there will be projects on older versions and overtime libraries drop support with later releases.

**Comment by WarenGonzaga** [comment]
Awesome @JohnDoePBabu! I'll make a requirement on the readme for this one.

**Comment by JohnDoePBabu** [comment]
Found an issue with this. I overlooked the fact that this has to work as a library on the browser as well.
Got does not support the browser
![image](https://user-images.githubusercontent.com/20773727/97874655-5324d500-1d3f-11eb-93e1-c935690cb814.png)
I will quickly change to an alternative, maybe our original choice - Axios.

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu which means we can't use it to return a value to browser?

**Comment by JohnDoePBabu** [comment]
yeah, we cannot use it as a package within javascript executed by a browser. So can't use directly on websites, front end framework (React, Angular) based apps.

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu so we will go back to our original plan for axios? what else our options?

**Comment by JohnDoePBabu** [comment]
Alternatives suggested by request https://github.com/request/request/issues/3143.
If we need browser and NodeJS support, Axios is the only viable option as far as I can tell.
Funnily, I don't think even request worked well as a package on the browser.

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu jackpot! Well let's go with axios...

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu I'm going to close this now let's continue the conversation here #2
