### ISSUE TITLE
Transition to Axios

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/buymeacoffee.js#2]
I just want to replace "request" to "Axios" for more better feature.

**Comment by JohnDoePBabu** [comment]
Are you open to got?
https://www.npmjs.com/package/got
very similar to request and after request got deprecated, a lot of people seem to be moving to got.
https://nodesource.com/blog/express-going-into-maintenance-mode

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu is it better to axios?

**Comment by JohnDoePBabu** [comment]
I would say so.
This [link](https://nodesource.com/blog/express-going-into-maintenance-mode) compares some features between the two.
Also, I found the response structure much more similar to request.
It is not yet as popular as axios, but is quickly gaining attraction.

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu agree... I saw the link and I guess this is better than axios... let's use the latest tech as possible.

**Comment by WarenGonzaga** [comment]
Referencing #10 as we can't use Got for browser.

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu submit PR for undoing...

**Comment by WarenGonzaga** [comment]
Thanks @JohnDoePBabu
