### ISSUE TITLE
migrate to webpack

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/buymeacoffee.js#21]
This is from discussion #20 to move from GulpJS to Webpack for the building and development process. This will improve the maintainability of the project.

**Comment by WarenGonzaga** [comment]
> Hey can i work on this issue? I can make a simple webpack.config.js file with babeljs. It will bundle all the js files into a single bundle.js file. I won't remove existing gulp configuration. I'll just add a new script ` yarn webpack` This will make a bundle.js file in 'build' directory If there are any more requirements then let me know :)

Before we work on the webpack can you try to look at this issue #23

We can't just convert it to webpack if that issue is still present.

Also as an additional, if you can replicate the functionalities in the gulp file that would be good.

The important is to add the license in production-ready files.

**Comment by SaharshSamir** [comment]
> > Hey can i work on this issue? I can make a simple webpack.config.js file with babeljs. It will bundle all the js files into a single bundle.js file. I won't remove existing gulp configuration. I'll just add a new script ` yarn webpack` This will make a bundle.js file in 'build' directory If there are any more requirements then let me know :)
> 
> Before we work on the webpack can you try to look at this issue #23
> 
> We can't just convert it to webpack if that issue is still present.
> 
> Also as an additional, if you can replicate the functionalities in the gulp file that would be good.
> 
> The important is to add the license in production-ready files.

okay sure!
