### ISSUE TITLE
migrate to typescript

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/buymeacoffee.js#57]
Move the project to typescript for easier maintenance. ✌

**Comment by AmrMonier** [comment]
if this is not done yet i would love to work on it

**Comment by thomasbnt** [comment]
> if this is not done yet i would love to work on it

Hello ! Of course, you can!

**Comment by AmrMonier** [comment]
@thomasbnt i have just added the PR https://github.com/warengonzaga/buymeacoffee.js/pull/60

**Comment by warengonzaga** [comment]
Awesome @AmrMonier, let me take a look! Thanks for your contribution!

**Comment by warengonzaga** [comment]
Waiting to merge...

**Comment by warengonzaga** [comment]
Added in #56
